(declare-fun temp0_1 () (_ BitVec 64))
(declare-fun ARGNAME_input_NAMEEND_DIM () (_ BitVec 64))
(declare-fun temp0_3 () (_ BitVec 64))
(declare-fun temp0_2 () (_ BitVec 64))
(declare-fun temp0_5 () (_ BitVec 64))
(declare-fun temp0_4 () (_ BitVec 64))
(declare-fun temp0_6 () (_ BitVec 64))
(declare-fun var789336 () (_ BitVec 64))
(declare-fun temp0_7 () (_ BitVec 64))
(declare-fun var66452 () (_ BitVec 64))
(declare-fun var66448 () (_ BitVec 64))
(declare-fun temp0_8 () (_ BitVec 64))
(declare-fun var1051480 () (_ BitVec 64))
(declare-fun var66447 () (_ BitVec 64))
(declare-fun var67546 () (_ BitVec 64))
(assert (= temp0_1 #x0000000000000001))
(assert (or false (= ARGNAME_input_NAMEEND_DIM temp0_1)))
(assert (= temp0_3 #x0000000000000000))
(assert (= temp0_2 temp0_3))
(assert (= temp0_5 #x0000000000000001))
(assert (= temp0_4 temp0_5))
(assert (= temp0_6 #x0000000000000001))
(assert (= var789336 temp0_6))
(assert (= temp0_7 #x0000000000000000))
(assert (= var66452 temp0_7))
(assert (= var66448 var66452))
(assert (= temp0_8 #x0000000000000001))
(assert (= var1051480 temp0_8))
(assert (= var66447 var66448))
(assert (= var67546 var66447))
(model-add temp0_1 () (_ BitVec 64) #x0000000000000001)
(model-add ARGNAME_input_NAMEEND_DIM () (_ BitVec 64) #x0000000000000001)
















