[workspace]
authors = [""]
channels = ["conda-forge"]
name = "ACETest"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "==3.10"
bs4 = ">=4.13.5,<5"
termcolor = ">=3.1.0,<4"

[pypi-dependencies]
tensorflow = "==2.9"
torch = "==1.13.0"
z3-solver = ">=4.15.3.0, <5"
sysv-ipc = ">=1.1.0, <2"
protobuf = "==3.20.*"
numpy = "<2"
