(declare-fun temp4_1 () (_ BitVec 64))
(declare-fun var791270 () (_ BitVec 64))
(declare-fun temp4_2 () (_ BitVec 64))
(declare-fun ARGNAME_keepdim_NAMEEND () (_ BitVec 64))
(declare-fun temp4_4 () (_ BitVec 64))
(declare-fun temp4_3 () (_ BitVec 64))
(declare-fun temp4_5 () (_ BitVec 64))
(declare-fun var4008049 () (_ BitVec 64))
(assert (= temp4_1 #x0000000000000001))
(assert (= var791270 temp4_1))
(assert (= temp4_2 #x0000000000000001))
(assert (= ARGNAME_keepdim_NAMEEND temp4_2))
(assert (= temp4_4 #x0000000000000001))
(assert (= temp4_3 temp4_4))
(assert (= temp4_5 #x0000000000000000))
(assert (= var4008049 temp4_5))
(model-add temp4_1 () (_ BitVec 64) #x0000000000000001)
(model-add var791270 () (_ BitVec 64) #x0000000000000001)
(model-add temp4_2 () (_ BitVec 64) #x0000000000000001)
(model-add ARGNAME_keepdim_NAMEEND () (_ BitVec 64) #x0000000000000001)






